### PR TITLE
staging: update flake.lock

### PR DESCRIPTION
**Pull request by markuskowa**
The latest nixpkgs-staging merge broke some packages:
- [x]  polyply
- [x] ambertools (via `python312.scipy`)
- [x] python3.ambertools
- [x] psi4

Upstream failures:
* ~~python3Packages.simple-dftd3~~ 
* ~~siesta~~
* python3Packages.dscribe
* python3Packages.iodata (also needs an update?)

CC @sheepforce

### CODE REVIEW

**Comment by sheepforce** [comment]
`tblite` builds just fine with `nix build .#tblite` in this branch. Which error did you get?

**Comment by markuskowa** [comment]
`tblite` itself builds just fine, but every package that consumes `tblite` now fails to evaulate:
`nix-build release.nix --show-trace -A qchem.xtb`:
```
....
       … while calling the 'isString' builtin
         at /nix/store/4gi6i3zx2p0phw5klwhy1h4fh36kp0lh-source/lib/meta-types.nix:173:19:
          172|       name = "either<${t1.name},${t2.name}>";
          173|       verify = v: v1 v || v2 v;
             |                   ^
          174|     };

       … while evaluating the attribute 'changelog'
         at /nix/store/4gi6i3zx2p0phw5klwhy1h4fh36kp0lh-source/pkgs/development/libraries/science/chemistry/tblite/default.nix:111:5:
          110|     homepage = "https://github.com/tblite/tblite";
          111|     changelog = "https://github.com/tblite/tblite/releases/tag/${finalAttrs.src.tag}";
             |     ^
          112|     platforms = lib.platforms.linux;

       … while evaluating a path segment
         at /nix/store/4gi6i3zx2p0phw5klwhy1h4fh36kp0lh-source/pkgs/development/libraries/science/chemistry/tblite/default.nix:111:64:
          110|     homepage = "https://github.com/tblite/tblite";
          111|     changelog = "https://github.com/tblite/tblite/releases/tag/${finalAttrs.src.tag}";
             |                                                                ^
          112|     platforms = lib.platforms.linux;

       error: cannot coerce null to a string: null

       note: trace involved the following derivations:
       derivation 'xtb-6.7.1'

```

(I do not understand why it suddenly fails in `.meta`)

**Comment by sheepforce** [comment]
Alright, I think I've got them all.

**Comment by markuskowa** [comment]
> Alright, I think I've got them all.

We just peeled off the first layer. 

Do we still need `qchem.python311.ambertools`?

```
in job ‘qchem.python311.ambertools’:
error:
       … while evaluating the attribute 'drvPath'
         at /nix/store/4gi6i3zx2p0phw5klwhy1h4fh36kp0lh-source/lib/customisation.nix:415:11:
          414|         // {
          415|           drvPath =
             |           ^
          416|             assert condition;

       … while calling the 'derivationStrict' builtin
         at «nix-internal»/derivation-internal.nix:37:12:
           36|
           37|   strict = derivationStrict drvAttrs;
             |            ^
           38|

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: sphinx-9.1.0 not supported for interpreter python3.11
```

and more:
-  tests.cp2k
```
ok 3 H2O-gga
not ok 4 bench_dftb Energy
# (in test file /nix/store/0rjf9s4fbrrkxryhibnxrsmkm5n6bpvr-cp2k.bats, line 33)
#   `grep 'ENERGY|' bench_dftb.out | grep '\-16687.6956289'' failed
ok 5 H2O-gga Energy
```
-  tests.nwchem
```
not ok 1 Run-nwchem
# (in test file /nix/store/ik4p1vry4qscx6n3rp9575cdlz6gwli1-nwchem.bats, line 21)
#   `mpirun -np $TEST_NUM_CPUS nwchem nwchem.inp > nwchem.out' failed with status 16
# Abort(874136592): Fatal error in internal_Init: Internal MPI error!, error stack:
# internal_Init(70)...............: MPI_Init(argc=0x7fffffffba8c, argv=0x7fffffffba80) failed
# MPII_Init_thread(204)...........:
# MPIR_pmi_init(225)..............:
# check_MPIR_CVAR_PMI_VERSION(167):  Runtime environment uses unsupported PMI version PMIx. Aborting.
# Abort(874136592): Fatal error in internal_Init: Internal MPI error!, error stack:
# internal_Init(70)...............: MPI_Init(argc=0x7fffffffba8c, argv=0x7fffffffba80) failed
# MPII_Init_thread(204)...........:
# MPIR_pmi_init(225)..............:
# check_MPIR_CVAR_PMI_VERSION(167):  Runtime environment uses unsupported PMI version PMIx. Aborting.
# --------------------------------------------------------------------------
#
# prterun detected that one or more processes exited with non-zero status,
# thus causing the job to be terminated. The first process to do so was:
#
#    Process name: [prterun-localhost-58@1,0]
#    Exit code:    16
# -------------------------------------------------------------------------- 
```

**Comment by sheepforce** [comment]
> Do we still need qchem.python311.ambertools?

Nope, basically only runs with 3.12. Upstream strictly uses Conda with 3.12 and nothing else.

I will see what I can do for CP2K.

**Comment by markuskowa** [comment]
Do we the need the python-3.11 builds for anything else?
These are still on the current list:
```
python3.11-adcc-0.15.17 	x86_64-linux
python3.11-autocas-3.0.0 	x86_64-linux
python3.11-biopython-1.86 	x86_64-linux
python3.11-cgsmiles-1.0.1 	x86_64-linux
python3.11-dftbplus-unstable-2025-04-11 	x86_64-linux
python3.11-dptools-unstable-2025-04-11 	x86_64-linux
python3.11-gau2grid-2.0.8 	x86_64-linux
python3.11-moltemplate-2.22.4 	x86_64-linux
python3.11-pdbfixer-1.12 	x86_64-linux
python3.11-polyply-1.8.0 	x86_64-linux
python3.11-PyCheMPS2-1.8.12 	x86_64-linux
python3.11-pymbar-4.0.3 	x86_64-linux
python3.11-pyPHSPU-2022-05-23 	x86_64-linux
python3.11-pyQDng-0.10.0 	x86_64-linux
python3.11-pyquante2-unstable-2024-01-23 	x86_64-linux
```

**Comment by sheepforce** [comment]
No, since vmd-python hasn't updated for some time and we've declared it broken, I think there is no need for Python 3.11 anymore.

**Comment by sheepforce** [comment]
CP2K is interesting. The example runs and produces a converged energy (extremely loose convergence settings, though):

```
cp2k> #  ------------------------------ Linear scaling SCF -----------------------------
cp2k> #  eps_scf:                                                              0.100E-04
cp2k> #  eps_filter:                                                           0.100E-05
cp2k> #  mixing_fraction:                                                      0.450E+00
cp2k> #  max_scf:                                                                     20
cp2k> #  fixed chemical potential (mu)                                                 F
cp2k> #  has unit metric:                                                              F
cp2k> #  Computing inv(S):                                                             T
cp2k> #  Computing sqrt(S):                                                            T
cp2k> #  Computing S preconditioner                                                    F
cp2k> #  S sqrt method:                                                     NEWTONSCHULZ
cp2k> #  S sqrt order:                                                                 3
cp2k> #  Extrapolation order:                                                          4
cp2k> #  S preconditioner type                                                      NONE
cp2k> #  Polarized Atomic Orbitals (PAO)                                               F
cp2k> #  Purification method                                   Trace resetting 4th order
cp2k> #  Cluster type                                                          MOLECULAR
cp2k> #  Computing Chebyshev                                                           F
cp2k> #  -------------------------------------------------------------------------------
cp2k> #
cp2k> #
cp2k> #
cp2k> #  Energy with the initial guess:    -13935.989884279
cp2k> #
cp2k> #
cp2k> #  SCF     1    -16293.029480866    -16293.029480866   40.299548
cp2k> #
cp2k> # *********************************************************
cp2k> #  Using MIXING_FRACTION=0.450 to mix KS matrix:  iscf=  2
cp2k> #  KS_nw=0.450*KS + 0.550*KS_old
cp2k> # *********************************************************
cp2k> #
cp2k> #  SCF     2    -16312.364394692       -19.334913826   39.137279
cp2k> #
cp2k> # *********************************************************
cp2k> #  Using MIXING_FRACTION=0.450 to mix KS matrix:  iscf=  3
cp2k> #  KS_nw=0.450*KS + 0.550*KS_old
cp2k> # *********************************************************
cp2k> #
cp2k> #  SCF     3    -16316.053305224        -3.688910532   38.544669
cp2k> #
cp2k> # *********************************************************
cp2k> #  Using MIXING_FRACTION=0.450 to mix KS matrix:  iscf=  4
cp2k> #  KS_nw=0.450*KS + 0.550*KS_old
cp2k> # *********************************************************
cp2k> #
cp2k> #  SCF     4    -16316.740862139        -0.687556916   38.033693
cp2k> #
cp2k> # *********************************************************
cp2k> #  Using MIXING_FRACTION=0.450 to mix KS matrix:  iscf=  5
cp2k> #  KS_nw=0.450*KS + 0.550*KS_old
cp2k> # *********************************************************
cp2k> #
cp2k> #  SCF     5    -16316.868119199        -0.127257059   38.686161
```

but it doesn't look as if it would get close to `-16687.6956289` ... The input upstream hasn't changed. So there must be something subtle numerical, that only touches DFTB but not DFT. Crazy :sweat_smile:

**Comment by sheepforce** [comment]
Apparently the default Alpha parameter in the Ewald summation has changed this commit here https://github.com/cp2k/cp2k/commit/cccd2f3#diff-ea278fcf32a8f7eda45fe1d5785f4a6caa4c5df38dd5d83cdc90eeb45836f067R433-L432 , which influences the energies of the DFTB example. The new values is most likely correct with these settings. Fair enough. It is a performance and not an accuracy benchmark in CP2K.

**Comment by markuskowa** [comment]
This will take a while. Further updating the flake.lock just added more issues.

**Comment by sheepforce** [comment]
> python314.pyscf

https://github.com/NixOS/nixpkgs/pull/546291

**Comment by sheepforce** [comment]
> vtk

`nix build .#python3.pkgs.vtk` builds fine on current master of nixpkgs

**Comment by sheepforce** [comment]
> tests.nwchem

Hopefully fixed by https://github.com/NixOS/nixpkgs/pull/546593

**Comment by markuskowa** [comment]
...and the saga goes on:
polyply:
```
pytest flags: -m pytest -k not\ \(test_integration_protein\)
============================= test session starts ==============================
platform linux -- Python 3.14.6, pytest-9.1.1, pluggy-1.6.0
rootdir: /build/source
configfile: pyproject.toml
plugins: typeguard-4.5.2
collected 530 items / 1 error / 30 deselected / 500 selected                   

==================================== ERRORS ====================================
__________ ERROR collecting polyply/tests/test_simple_seq_parsers.py ___________
polyply/tests/test_simple_seq_parsers.py::test_sequence_parses: in "parametrize" the number of names (1):
  ['extension']
must be equal to the number of values (3):
  txt
=============================== warnings summary ===============================
../../nix/store/0n1l6j7ibd69gikxdjmriwy0hdf7266y-python3.14-numba-0.66.0/lib/python3.14/site-packages/numba/np/npdatetime_helpers.py:29
  /nix/store/0n1l6j7ibd69gikxdjmriwy0hdf7266y-python3.14-numba-0.66.0/lib/python3.14/site-packages/numba/np/npdatetime_helpers.py:29: DeprecationWarning: The 'generic' unit for NumPy timedelta is deprecated, and will raise an error in the future. This includes implicit conversion of bare integers (e.g. `+ 1`).Please use a specific unit instead.
    NAT = np.timedelta64('nat').astype(np.int64)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR polyply/tests/test_simple_seq_parsers.py - Failed: polyply/tests/test_simple_seq_parsers.py::test_sequence_parses: in ...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
```


python3.ambertools:
```
pytraj/datasets/cast_dataset.cpp:24693:46: error: too few arguments to function ‘int _PyLong_AsByteArray(PyLongObject*, unsigned char*, size_t, int, int, int)’
24693 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
      |                           ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
24694 |                                               bytes, sizeof(val),
      |                                               ~~~~~~~~~~~~~~~~~~~
24695 |                                               is_little, !is_unsigned);
      |                                               ~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /nix/store/gxzhl7aaiid7zp3y47jqqiq7zg5mqpwp-python3-3.14.6/include/python3.14/longobject.h:171,
                 from /nix/store/gxzhl7aaiid7zp3y47jqqiq7zg5mqpwp-python3-3.14.6/include/python3.14/Python.h:92:
/nix/store/gxzhl7aaiid7zp3y47jqqiq7zg5mqpwp-python3-3.14.6/include/python3.14/cpython/longobject.h:84:17: note: declared here
   84 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
      |                 ^~~~~~~~~~~~~~~~~~~
```

**Comment by sheepforce** [comment]
Alright, both should be fixed now and AmberTools should also work with other python versions than 3.12 now.

**Comment by markuskowa** [comment]
@sheepforce Thanks!

Almost done. Now it is dscribe and iodata which need to be fixed upstream. And psi4, which now tries to download some dependencies directly!?

image

**Comment by sheepforce** [comment]
> iodata 

https://github.com/NixOS/nixpkgs/pull/551155

> dscribe

https://github.com/NixOS/nixpkgs/pull/551156

**Comment by sheepforce** [comment]
Alright, Psi4 also fixed and updated https://github.com/psi4/psi4/releases/tag/v1.11

**Comment by markuskowa** [comment]
Clean against nixpkgs e99d0bffd2a4cafb19335ea4ec95edc9ca23a0a4


image

**Comment by sheepforce** [comment]
Finally :sob::smile:

**Comment by markuskowa** [comment]
And finally we move on...
